language: python

# Use container-based infrastructure
sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  include:
   - env: TOXENV=py27-dj18-sqlite
   - env: TOXENV=py33-dj18-sqlite
   - env: TOXENV=py34-dj18-sqlite
   - env: TOXENV=py27-dj19-sqlite
   - env: TOXENV=py34-dj19-sqlite
   - env: TOXENV=py27-dj110-sqlite
   - env: TOXENV=py34-dj110-sqlite
   - env: TOXENV=py35-dj110-sqlite
   - env: TOXENV=py27-dj18-postgres
   - env: TOXENV=py33-dj18-postgres
   - env: TOXENV=py34-dj18-postgres
   - env: TOXENV=py27-dj19-postgres
   - env: TOXENV=py34-dj19-postgres
   - env: TOXENV=py27-dj110-postgres
   - env: TOXENV=py34-dj110-postgres
   - env: TOXENV=py35-dj110-postgres

install:
  - pip install tox
  - createdb modelcluster

script:
  tox
